### ISSUE TITLE
Is there a way to show history tab/page in the mind map workspace itself? 

### ISSUE THREAD

**Issue by diwakaran1dan** [wanglin2/mind-map#34]
Hi @wanglin2 sir, is there is a way to save the developed mind map and store it in history tab/page in the workspace itself like portfolio of the project, option to delete/share those mind map histories?
And option to export .Smm/.json/.png/.pdf though email

It will be helpful for users using this tool simultaneously.

**Comment by diwakaran1dan** [comment]
*showing the saved mindmap history like basic style/themes/structure window

**Comment by diwakaran1dan** [comment]
@wanglin2 sir.. kindly look at this image sir.. i ask for a feature like that.. if it is possible, kindly try sir
![image](https://user-images.githubusercontent.com/42892061/191770064-0f38b9a9-ef41-4ddc-a90a-4c7ee149873f.png)

**Comment by wanglin2** [comment]
What is history when I close the browser window? Or create it manually?

**Comment by diwakaran1dan** [comment]
@wanglin2  yes sir you were right, I mean saving the history when you create it manually or by clicking the save button, sir. 


![image](https://user-images.githubusercontent.com/42892061/192078683-1e209513-4d16-4f49-883b-f9d166cd7c7e.png)

**Comment by wanglin2** [comment]
This function may not be added because the data is stored locally through the browser, so the capacity is limited. It supports the storage of historical versions, which will soon reach the upper limit. However, I recently added the function of directly editing local files on the computer, so you can manually create historical versions through the [另存为/Save As] option.
